server.port=9090

### db
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/vod
#spring.datasource.username=root
#spring.datasource.password=mysql

###
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/lab

#spring.jpa.show-sql=true

vod.url=http://localhost:8080


spring.kafka.producer.bootstrap-servers=localhost:8097
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
