server.port=9090
spring.application.name=stock-recommendation

# MongoDB configuration
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/recommendations?authSource=admin

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:8097
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer