###
GET http://localhost:8080/cinemas
Accept: application/xml

###
GET http://localhost:8080/cinemas?movieId=1

###
GET http://localhost:8080/movies/1/cinemas

###
GET http://localhost:8080/cinemas/1

###
OPTIONS http://localhost:8080/movies

###
HEAD http://localhost:8080/movies

###
GET http://localhost:8080/movies/1

###
GET http://localhost:8080/cinemas/1/movies

###
POST http://localhost:8080/movies
Content-Type: application/json

{
  "title": "Batman",
  "poster": "http://gapla.fn.org.pl/public/cache/P21829-483x700.jpg",
  "directorId": 3
}



